import { LoadingOverlay } from "@mantine/core";
import Head from "next/head";
import Hero from "../components/Hero";
import css from "../styles/Home.module.css"
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />      
        </main>
      </div>
      </Layout>
  );
}

